### ISSUE TITLE
use something different to Jack for lambdas to lower required SDK version

### ISSUE THREAD

**Issue by wtjerry** [Che4ter/platypus-android#1]

**Comment by Che4ter** [comment]
Most of the Java 8 Features including Lambdas,Method References and Type Annotations are supported in the latest android studio 2.4 preview 7
see: 
https://android-developers.googleblog.com/2017/04/java-8-language-features-support-update.html 
https://developer.android.com/studio/preview/features/java8-support.html

the only problem is, that the min sdk version is still >= 24 
I removed jack dependencies in https://github.com/Che4ter/platypus-android/commit/b1402ecb3bcc028b93982252bfc815fe05a05188
