### ISSUE TITLE
Implement Swipe/Pull to Refresh on Feedbackview to trigger new sync

### ISSUE THREAD

**Issue by Che4ter** [Che4ter/platypus-android#2]
It should be easy to implement a swipe to refresh function. https://developer.android.com/training/swipe/add-swipe-interface.html

Here I found a tutorial, how to implement it on tabs.

on answer 1:
http://stackoverflow.com/questions/32683513/sliding-tabs-with-recycleview-fragments-and-swipe-to-refresh

**Comment by wtjerry** [comment]
implemented in commit 515c81e0fc2cbf18734847d4477d7e9134afb47d
